name: medical-foundation
channels:
  - defaults
  - conda-forge
  - pytorch
  - xformers
dependencies:
  - torchmetrics=0.10.3
  - iopath=0.1.9
  - pytorch=2.0.0
  - xformers=0.0.18
  - omegaconf=2.3.0
  - fvcore
  - pip
  - python=3.9
  - torchvision=0.15.0
  - bokeh=3.2.1
  - scikit-image=0.19.3
  - colorcet=3.0.1
  - matplotlib=3.7.2
  - pandas=2.1.4
  - datashader=0.15.2
  - holoviews=1.17.1
  - pip:
    - bottleneck==1.3.5
    - brotlipy==0.7.0
    - cuml-cu11==23.6.0
    - cytoolz==0.12.0
    - datashader==0.15.2
    - detectron2==0.6
    - easydict==1.10
    - einops==0.6.2rc0
    - fairscale==0.4.13
    - flake8==6.0.0
    - fqdn==1.5.1
    - h5py==3.9.0
    - holoviews==1.17.1
    - imagecodecs==2023.1.23
    - install==1.3.5
    - isoduration==20.11.0
    - jsonpointer==2.4
    - jupyter==1.0.0
    - jupyterlab==4.0.2
    - kornia==0.6.12
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - munkres==1.1.4
    - nltk==3.8.1
    - numexpr==2.8.7
    - opencv-python==4.8.0.74
    - openpyxl==3.1.2
    - openslide-python==1.3.1
    - pip-chill==1.0.3
    - pre-commit==3.3.3
    - pydrive2==1.16.1
    - pyqt5-sip==12.11.0
    - pysocks==1.7.1
    - scikit-image==0.19.3
    - sip==6.6.2
    - submitit==1.4.5
    - torchmetrics==0.10.3
    - transformers==4.30.2
    - triton==2.0.0
    - umap-learn==0.5.4
    - uri-template==1.3.0
    - wandb==0.15.5
    - webcolors==1.13
    - xformers==0.0.18
